include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**

linter:
  rules:
    - prefer_single_quotes
    - prefer_final_locals
    - unnecessary_lambdas
    - directives_ordering
